[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install -g pnpm", "pnpm install"]

[phases.build]
cmds = [
  "pnpm --filter @privateers/ui build",
  "pnpm --filter storybook build"
]

[start]
cmd = "npx serve apps/storybook/dist -s -l 3000"
